In [4]:
%%HTML
<style>
    body {
        --vscode-font-family: "Comic Sans MS";
    }
</style>

In [5]:
# imports
import torch
import torch.nn as nn

## Initializing a linear layer

In [6]:
linear = nn.Linear(5, 10) # in_features x out_features

## Mathematics 

x = input  
out = linear(x)  
out = x * wT + b  

In [7]:
w = linear.weight
w, w.shape

(Parameter containing:
 tensor([[-0.3216,  0.2571,  0.3775, -0.0710,  0.0808],
         [-0.0540,  0.4249, -0.2865, -0.4096, -0.2498],
         [-0.3567,  0.1327, -0.0067,  0.2657,  0.3833],
         [ 0.0922, -0.3572,  0.0815, -0.4438,  0.2567],
         [-0.2889, -0.4142,  0.3146,  0.3000, -0.2248],
         [ 0.2340, -0.0197,  0.2359,  0.3441,  0.1129],
         [ 0.4212, -0.0779, -0.1665,  0.3839, -0.0018],
         [ 0.2970, -0.2355,  0.0551,  0.2381,  0.1081],
         [ 0.4309,  0.1830,  0.3292,  0.3751, -0.1226],
         [ 0.1609,  0.4431, -0.1526,  0.0688, -0.0522]], requires_grad=True),
 torch.Size([10, 5]))

In [8]:
b = linear.bias
b, b.shape

(Parameter containing:
 tensor([-0.3138, -0.2444,  0.1954, -0.2383, -0.3031, -0.3036,  0.0982,  0.3253,
         -0.0587,  0.3930], requires_grad=True),
 torch.Size([10]))

## Total no of parameters
 
 parameters :  
 =  no of weights + no of bias  (if bias is True)  
 =  in_feature * out_feature + out_feature

In [9]:
#calculated 
par_calc = w.shape[0] * w.shape[1] + w.shape[0] # out_features x in_features + bias(out_features)
par = sum(p.numel() for p in linear.parameters())
par, par_calc, par == par_calc

(60, 60, True)

## sample input

In [10]:
x = torch.randn(2, 10, 5)
x

tensor([[[ 0.4128,  0.5691, -1.3219,  1.1627, -0.2854],
         [-0.4560,  1.0063, -0.1352, -0.2218,  0.7237],
         [ 1.1138, -0.4026, -0.6635,  0.6933,  0.4720],
         [ 0.4500, -0.4214, -0.0448,  1.2405, -0.3072],
         [-0.1906,  0.4721, -0.2089,  0.3199,  2.3474],
         [-1.2073,  0.1005,  0.1652, -0.7644, -0.2573],
         [ 0.6366, -0.3258,  0.6872,  0.8834,  1.3310],
         [-0.8105,  0.6710,  0.8526, -1.0486,  0.4852],
         [-0.0408, -1.3647, -0.0912,  0.8115,  0.3182],
         [-1.1366, -0.3955, -0.7339,  0.3527, -0.0524]],

        [[ 1.3382, -0.8570, -1.5663, -0.0943,  0.2436],
         [-0.6634,  1.3843,  0.2105, -0.4957,  0.1216],
         [-0.0710,  0.4015,  0.4554,  1.3340,  0.2207],
         [ 1.4874, -0.8041, -0.4496, -0.3118, -0.3752],
         [ 0.2817, -0.5063,  2.2268,  1.8770, -0.4947],
         [ 0.6496,  1.4976,  0.4285, -2.1881,  0.3168],
         [-0.0126, -0.7871,  0.1960,  0.2699,  0.7589],
         [ 0.3288, -2.0334,  0.6810,  0.2015, 

In [11]:
out = linear(x)
out, out.shape

(tensor([[[-9.0477e-01, -5.1042e-02,  3.3206e-01, -1.1005e+00, -6.6096e-01,
           -1.6226e-01,  8.9471e-01,  4.8709e-01,  2.5935e-01,  1.0083e+00],
          [ 1.1478e-01,  1.5656e-01,  7.1094e-01, -3.6659e-01, -8.5991e-01,
           -4.5666e-01, -2.3614e-01, -2.9092e-02, -2.8751e-01,  7.3321e-01],
          [-1.0370e+00, -6.8729e-01,  1.1421e-01, -2.3230e-01, -5.6495e-01,
            1.0019e-01,  9.7444e-01,  9.3041e-01,  3.3129e-01,  5.1816e-01],
          [-6.9666e-01, -8.6612e-01,  1.9114e-01, -6.7931e-01,  1.6857e-01,
            1.9155e-01,  8.0483e-01,  8.1787e-01,  5.4633e-01,  3.8695e-01],
          [-4.3021e-02, -6.9116e-01,  1.3122e+00,  1.9126e-02, -9.4100e-01,
           -3.1812e-02,  1.3446e-01,  4.7593e-01, -2.9105e-01,  5.0298e-01],
          [ 1.9623e-01,  1.9351e-01,  3.3658e-01, -9.8836e-02, -1.1541e-01,
           -8.4115e-01, -7.3855e-01, -2.5763e-01, -7.6143e-01,  1.7891e-01],
          [-2.9808e-01, -1.3083e+00,  6.6538e-01, -5.7565e-02, -1.7003e-01,
      

## Verification

In [12]:
out_ = x @ w.mT + b
out_, out_.shape

(tensor([[[-9.0477e-01, -5.1042e-02,  3.3206e-01, -1.1005e+00, -6.6096e-01,
           -1.6226e-01,  8.9471e-01,  4.8709e-01,  2.5935e-01,  1.0083e+00],
          [ 1.1478e-01,  1.5656e-01,  7.1094e-01, -3.6659e-01, -8.5991e-01,
           -4.5666e-01, -2.3614e-01, -2.9092e-02, -2.8751e-01,  7.3321e-01],
          [-1.0370e+00, -6.8729e-01,  1.1421e-01, -2.3230e-01, -5.6495e-01,
            1.0019e-01,  9.7444e-01,  9.3041e-01,  3.3129e-01,  5.1816e-01],
          [-6.9666e-01, -8.6612e-01,  1.9114e-01, -6.7931e-01,  1.6857e-01,
            1.9155e-01,  8.0483e-01,  8.1787e-01,  5.4633e-01,  3.8695e-01],
          [-4.3021e-02, -6.9116e-01,  1.3122e+00,  1.9126e-02, -9.4100e-01,
           -3.1812e-02,  1.3446e-01,  4.7593e-01, -2.9105e-01,  5.0298e-01],
          [ 1.9623e-01,  1.9351e-01,  3.3658e-01, -9.8836e-02, -1.1541e-01,
           -8.4115e-01, -7.3855e-01, -2.5763e-01, -7.6143e-01,  1.7891e-01],
          [-2.9808e-01, -1.3083e+00,  6.6538e-01, -5.7565e-02, -1.7003e-01,
      

In [13]:
torch.allclose(out, out_)

True

## FLOPS:

Floating point operations: "*, +, -, /"  
Flops = no of Floating point operations per second

for linear layer :  
___
no of "*":  
= in_feature * out_feature * (rest of input dimension) [weights]  
if input shape = (2, 10, 5), in_feature = x.shape[-1] = 5, let out_feature = 10  
then, FLOP for * = 5 * 10 * 10 * 2 = 1000  
___

no of "+":  
= (in_feature-1) * out_feature [weights] * (rest of input dimension) + out_features[bias] * (rest of input dimension) 
if input shape = (2, 10, 5), in_feature = x.shape[-1] = 5, let out_feature = 10  
then, FLOP for * = 4 * 10 * 10 * 2 + 10 * 10 * 2 = 1000

total FLOP = 2000
total FLOP = 2 * no of "*" or no of "+" = 2 * 1000 = 2000

without bias:
if input shape = (2, 10, 5), in_feature = x.shape[-1] = 5, let out_feature = 10  
then, FLOP for * = 4 * 10 * 10 * 2  = 800

total FLOP = 1800

In [24]:
# without bias
flops =  x.numel() * w.shape[0] + x[:, :, :-1].numel()  * w.shape[0] 
flops

1800

In [27]:
# with bias
flops =  2 *x.numel() * w.shape[0] 
flops

2000

## sample example